
version: "2.4"
volumes:
  fpm-volume:
  grafana-volume:
  elasticsearch-volume:
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - TZ
      - "discovery.type=single-node"
    volumes:
      -  elasticsearch-volume:/usr/share/elasticsearch/data
  apigw:
    build: 
      context: ./apigw/
      dockerfile: ./Dockerfile
    ports:
      - 80:80
    environment:
      - TZ
  napui:
    build: 
      context: ./napui/
      dockerfile: ./Dockerfile
    ports:
      - 8080:80
    volumes:
      - fpm-volume:/etc/fpm
    environment:
      - TZ
  logstash:
    image: docker.elastic.co/logstash/logstash:7.17.0
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro
    ports:
      - 515:515
    environment:
      - TZ
  grafana:
    image: grafana/grafana-oss:9.2.1
    ports:
      - 3000:3000
    volumes:
      - grafana-volume:/var/lib/grafana
    environment:
      - TZ
  logstash-nginx-logs:
    image: docker.elastic.co/logstash/logstash:7.17.0
    volumes:
      - ./logstash-nginx-logs/logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro
    ports:
      - 516:515/udp
    environment:
      - TZ
